### ISSUE TITLE
request/testing-binaries

### ISSUE THREAD

**Issue by theggarcez** [imbushuo/DFRDisplayKm#1]
Hi, would be possible to have testing binaries? i installed the unsigned touchpad precision driver, might aswell install this one, but i dont have VS Studio installed, if it possible to provide it in releases or something would be nice, im currently on Win 1903 on MBP 13.3 2019
thanks

**Comment by imbushuo** [comment]
PTP drivers are all signed as of today. As for the DFR display driver, I don't think it is the time to release binary, as this project does not target final users. It requires other user-mode applications that supply the DFR content and handle touch input.
