### ISSUE TITLE
No DRF device found after i build and install the dirver 'DFRDisplayKm.inf'

### ISSUE THREAD

**Issue by darkcike** [imbushuo/DFRDisplayKm#2]
My device is Macbook pro 15,2
Hi, i have successfully build the driver and console program.
It shows suc when i install the driver.But the console program shows 'No DRF device found'.
It seems like 'var instancePath = DfrDeviceDiscovery.FindDfrDevice();'   this cann't get a device instant.

**Comment by darkcike** [comment]
UPDATE
Since you have merged 'DFRUsbCcgp.inf' and 'DFRDisplayKm.inf' into one, so i install 'DFRDisplayKm.inf' for 'apple touch bar', and then the apple touch bar disappeared, and i can NOT found a 'iBridge Display' device in device manager.

**Comment by imbushuo** [comment]
@darkcike Have you seen an unknown USB device under the composition device? If so, re-install the INF for that device too.

**Comment by darkcike** [comment]
After last time i install the driver for the 'apple touch bar',  the 'fn' button not working anymore, so i restored my system.Ater then, i can't build solution. It shows some certificate error.I can't solve it by reinstall the vs2019.
