### ISSUE TITLE
nothing display on the touchbar.

### ISSUE THREAD

**Issue by Naozumi520** [imbushuo/DFRDisplayKm#5]
Hi, I'm using a 16inch machine.  I have successfully build the driver and console program tho, but I can not found a 'iBridge Display' device in device manager.
Then I have only install the driver for "apple touch bar", after that I got two new device:
![image](https://user-images.githubusercontent.com/52615455/117259856-09997c00-ae81-11eb-8663-0de9e842ce0b.png)
After run the console program, I can make the function keys works but there's still nothing display on the touchbar.

**Comment by Naozumi520** [comment]
I finally figured out why it show nothings on the touchbar. After I saw the warning in DFRDisplayUm.Utility.Console, I just realized that the new machine have exist esc keys and make the touchbar smaller. After change the resolution size to 2008 * 60 in the code it just works fine. Thanks for your hardwork!

**Comment by modz2014** [comment]
@Naozumi520 any chance of getting this  signed so we can develope for this driver instead on running in test mode

**Comment by DevX-Cipher** [comment]
@Naozumi520 can't seem to get it to work on MacBook Pro 2019 13inch
